Repository Devil-Algorithm-Study/Devils_Algorithm, pull requests merged in 2025-09, with the labels that each got.

#8 [feat]: BOJ5639 구현 (재귀)
  Devil_Java/src/main/java/week01_recursion/gold/BOJ5639_jiyun.java
Labels: 양지윤

#9 [feat]: BOJ24060 구현 (재귀)
  Devil_Java/src/main/java/week01_recursion/silver/BOJ24060_jiyun.java
Labels: 양지윤

#11 [BOJ24060] 알고리즘 정렬 - 병합 수업 1
  .idea/Devils_Algorithm.iml
  .idea/misc.xml
  .idea/modules.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2025__9__8___9_31___.xml
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2025__9__8__오전_9_31_[변경]/shelved.patch
  .idea/shelf/Uncommitted_changes_before_Checkout_at_2025__9__8__오전_9_31_[변경]1/shelved.patch
  Devil_Java/src/main/java/week01_recursion/silver/BOJ24060_joshcho.java
  out/production/Devils_Algorithm/week01/gold/BOJ5639_jiyun.class
  out/production/Devils_Algorithm/week01/gold/BOJ5639_joshcho$TreeNode.class
  out/production/Devils_Algorithm/week01/gold/BOJ5639_joshcho.class
  out/production/Devils_Algorithm/week01/silver/BOJ24060_jiyun.class
  out/production/Devils_Algorithm/week01/silver/BOJ24060_joshcho.class
Labels: 조성호

#13 [feat] BOJ5639 구현
  Devil_C/week01_recursion/gold/BOJ5639_yujeong.c
  Devil_Python/week01_recursion/gold/BOJ5639_yujeong.py
Labels: 장유정

#14 [feat] BOJ24060 구현
  Devil_C/week01_recursion/sliver/BOJ24060_yujeong.c
  Devil_Python/week01_recursion/silver/BOJ24060_yujeong.py
Labels: 장유정

#15 BOJ24060 코드 추가
  .idea/vcs.xml
  .idea/workspace.xml
  Devil_Java/src/main/java/week01_recursion/silver/BOJ24060_dwoong.java
Labels: 정대웅

#17 [2주차] BOJ16463 - 13일의 금요일
  .idea/workspace.xml
  Devil_Java/src/main/java/week02_ExhaustiveSearch/silver/BOJ16463_joshcho.java
Labels: 조성호

#18 실버문제
  Devil_Python/week01_recursion/silver/BOJ16463_yujeong.py
Labels: 장유정

#25 [feat] Jiyun/week02 boj12100
  Devil_Java/src/main/java/week02_bruteforce/BOJ12100_jiyun.java
Labels: 양지윤

#38 Sanghun/week03 boj1744
  Devil_C/week03_greedy/sanghun/BOJ1744.c
  Devil_C/week03_greedy/sanghun/BOJ1744.exe
  Devil_C/week03_greedy/sanghun/BOJ2217.c
  Devil_C/week03_greedy/sanghun/BOJ2217.exe
  Devil_C/week03_greedy/sanghun/filename.c
  Devil_C/week03_greedy/sanghun/filename.exe
Labels: 박상훈
